language: node_js
node_js:
 - "0.10"
before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq 
 - sudo apt-get install -qq build-essential libmysqlclient-dev mysql-client g++-4.8
 - export CXX="g++-4.8" CC="gcc-4.8"
 - mkdir boosted
 - cd boosted
 - wget -O boost_headers_1_57_0.zip https://github.com/mmod/ci-deps/blob/master/boost_headers_1_57_0.zip?raw=true -P .
 - unzip -qq boost_headers_1_57_0.zip
 - sudo cp -R boost_headers_1_57_0/boost /usr/include
 - cd ..
 - sudo rm -r boosted
 - mysql -e "create database nktest;" -u root
 - mysql -e "create user 'nktestadm'@'localhost' identified by '^NKTestPass777$';" -u root
 - mysql -e "grant all privileges on nktest.* to 'nktestadm'@'localhost';" -u root
