language: node_js
node_js:
 - "0.11"
 - "0.10"
before_install:
 - sudo apt-get update -qq 
 - sudo apt-get install build-essential libmysqlclient-dev mysql-client
 - mkdir boosted
 - cd boosted
 - wget https://github.com/rikkotec/ci-deps/blob/master/boost_headers_1_56_0.zip?raw=true -P .
 - mv boost_headers_1_56_0.zip?raw=true boost_headers_1_56.0.zip
 - unzip boost_headers_1_56_0.zip
 - sudo cp -R boost /usr/include
 - cd ..
 - sudo rm -r boosted
 - mysql -e "create database nktest;" -u root
 - mysql -e "create user 'nktestadm'@'localhost' identified by '^NKTestPass777$';" -u root
 - mysql -e "grant all privileges on 'nktest'.* to 'nktestadm'@'localhost';" -u root
